### ISSUE TITLE
Incompatible node version

### ISSUE THREAD

**Issue by saleh-tavassoli** [udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter#7]
Since Async functions are not supported in Node versions older than 7.6 that would be a great idea to provide information regarding proper Node version in README file. 
As I initially had Node version 6.9.5 I got following error as I was trying to start Frontend.

```yarn start
yarn run v1.17.3
$ node src/server/index.js
/udacity/nd032-c3-asynchronous-programming-with-javascript-project-starter/src/server/index.js:18
app.get('/', async (req, res) => {
                   ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by UAnjali** [comment]
Hi,
Thanks for suggesting the issue. We would request you to raise a PR for the same.
Thank you
